#lang info
(define collection "synology-decrypt")
(define deps '(("base64-lib" #:version "1.1")
               ("crypto-lib" #:version "1.9")
               ("lz4-lib" #:version "1.3")
               "base"))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib" "benchmark" "plot-lib"))
(define scribblings '(("scribblings/synology-decrypt.scrbl" ())))
(define pkg-desc "A command line tool and library to decrypt Synology Cloudsync encrypted files.")
(define version "0.4")
(define pkg-authors '(racket-packages@me.nikhilism.com))
(define license 'Apache-2.0)
