# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2019, macOS-12, ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: Bogdanp/setup-racket@v1.9
        with:
          architecture: x64
          distribution: full
          variant: 'CS'
          version: '8.6'
      
      # Run tests
      - run: raco pkg install --no-docs --auto --name synology-decrypt
      - run: raco setup --check-pkg-deps --unused-pkg-deps synology-decrypt
      - run: raco test -x -p synology-decrypt

      # Runs a single command using the runners shell
      - name: "Create binary release"
        run: raco exe --vv -o synology-decrypt main.rkt
          # This workflow contains a single job called "build"
      - run: ls -lh
 
